name: Development Workflow

on:
  push:
    branches:
      - "dev/**"
env:
  docker_username: ${{ github.actor }}
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}

jobs:
  Build:
    runs-on:  ubuntu-latest
    container:
      image: gradle:6-jdk11
    steps:
      - name: Clone down repository 
        uses: actions/checkout@v4
      - name: Run build-app.sh
        run: ci/build-app.sh
      - name: Run unit-test-app.sh
        run: ci/unit-test-app.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: .
          include-hidden-files: true

  Linting:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Run linting
        uses: super-linter/super-linter/slim@v7
        env:
          DEFAULT_BRANCH: "dev/**"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true

  Docker-image:
    runs-on: ubuntu-latest
    needs: Build
    permissions:
      packages: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: build docker
        run: bash ci/build-docker.sh
    
